---
server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amcdougall/spring-cloud-config-demo
          #username:uname
          #password:pass